Switch component
Zalart/angular-sandbox pull request #1
Opened 2022-03-18 09:29 UTC by Zalart

2022-03-18 10:36 UTC, stepn1k requested changes

2022-03-18 10:36 UTC, stepn1k commented on src/app/common/directives/switch.directive.ts
> +}
Круто что использовал директиву но она тут к сожалению не нужна. Объясню почему)
У тебя есть компонент свитча. 
Компонент состоит из трех частей:
- Шаблон
- Стили
- Логика

У тебя получился шаблон стили и директива.
Предположим тебе надо добавить новое свойство в компонент которое как то зависит от активного состояния?
Знает ли сейчас компонент что-нибудь о своем состоянии?
Не знает) компонент вообще ничего не знает, все лежит в директиве.
В дополнении к этому чтобы переиспользовать компонент ты должен помимо трех основных частей тащить еще и директиву за собой)

Можно ли использовать директиву где то в других местах кроме твоего компонента? 
- Ну использовать конечно можно но смысла 0. Все твои стили инкапсюлированы в этом компоненте и директива для других блоков бесполезна, она будет просто добавлять “on” класс)

2022-03-19 09:02 UTC, stepn1k requested changes

2022-03-19 09:02 UTC, stepn1k commented on src/app/common/components/switch/switch.component.html
> +         [ngClass]="{on: isSwitched}"
ngClass в основном используется для работы с несколькими классами)

Есть более лаконичная запись [class.on]="isSwitched"

2022-03-19 09:02 UTC, stepn1k commented on src/app/common/components/switch/switch.component.html
> +<div class="text">{{isSwitched ? 'ON' : 'OFF' }}</div>
Старайся минимизировать логику в шаблоне.

для всей логики есть у тебя есть компонент, старайся придерживаться подходам фреймворка

-логику в шаблонах сложно тестировать
-шаблон будет сложнее читать когда условия станет > 1)
В данном случае лучше будет сделать геттер

get statusLabel(): string {
return this.isActive ? 'ON' : 'OFF';
}

{{ statusLabel }}

2022-03-19 09:02 UTC, stepn1k commented on src/app/common/components/switch/switch.component.ts
> +  this.isSwitched = (<HTMLInputElement>event.currentTarget).checked;
В данном случае это избыточно) можно было просто сделать this.isSwitched = !this.isSwitched;

но если хочешь напрямую вытянуть значение из интупа таким способом: можно сделать так

 <input #checkBox(имя референса может быть любым) (change)="onSwitchChange(checkBox)" - и ссылку передаешь в функцию
 
 а в компоненте получается вот так:

 onSwitchChange(value: HTMLInputElement) {
    this.isSwitched = value.checked;
  }

2022-03-20 10:36 UTC, Zalart commented on src/app/common/components/switch/switch.component.html
> +         [ngClass]="{on: isSwitched}"
Done

2022-03-20 10:40 UTC, Zalart commented on src/app/common/components/switch/switch.component.ts
> +  this.isSwitched = (<HTMLInputElement>event.currentTarget).checked;
Refactored

2022-03-20 10:40 UTC, Zalart commented on src/app/common/components/switch/switch.component.html
> +<div class="text">{{isSwitched ? 'ON' : 'OFF' }}</div>
getter implemented

2022-03-21 06:10 UTC, stepn1k approved these changes

2022-03-21 06:44 UTC, merged